environment:
  nodejs_version: "14.15.4"

image:
  - Ubuntu
  - Visual Studio 2019

install:
  - sh: nvm install --lts
  - sh: PACK_VER=$(python3 -c "import json; x=open(\"package.json\",\"r\").read(); print(json.loads(x)[\"version\"]);")
  - ps: if ($isWindows) { Update-NodeJsInstallation $env:nodejs_version }
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - npm install

before_build:
  - node --version
  - npm run test
  - sh: echo $PACK_VER
  - ps: if ($isWindows) { echo $env:package_version }

build_script:
  - cmd: npm run package-win
  - sh: npm run package-linux

after_build:
  - sh: mv release-builds/markdown* release-builds/markdown-viewer
  - sh: cp builds/linux/* release-builds/markdown-viewer
  - sh: cd release-builds && tar czf ./markdown-viewer-linux-v$PACK_VER.tar.gz markdown-viewer
  - sh: cd .. && ls release-builds/
  - cmd: copy builds\win32\setup.iss .
  # release-builds\markdown-viewer-win32-ia32
  # - cmd: iscc .\setup.iss
  - cmd: curl --version
  - cmd: dir .